# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842fbb85870f103334361e40c16f23678b54c3a95304a215301a492b70193f674717cb46b0c33257c7c0b0503ede7262539788b4914828d095bbd795e5f5a939

test:
  secret_key_base: ca799f8d8f6f62d23fbfc5e970ad23af000618c5da96f5b08c8cfee8120905f01b4e3e6fee3db3c116eec185c407cc129c41dd1186f543ab8275472ce239b78f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
